// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebapiKodig.Domain.Persistence.Contexts;

namespace WebapiKodig.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebapiKodig.Domain.Models.Etiqueta", b =>
                {
                    b.Property<string>("CODIGO")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15);

                    b.Property<string>("PRODUTO")
                        .HasMaxLength(20);

                    b.Property<decimal>("QUANTIDADE");

                    b.Property<decimal>("SALDO");

                    b.HasKey("CODIGO");

                    b.ToTable("Etiquetas");
                });

            modelBuilder.Entity("WebapiKodig.Domain.Models.Produto", b =>
                {
                    b.Property<string>("CODIGO")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20);

                    b.Property<string>("DESCRICAO")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("TIPO")
                        .IsRequired()
                        .HasMaxLength(2);

                    b.Property<string>("UM")
                        .IsRequired()
                        .HasMaxLength(2);

                    b.HasKey("CODIGO");

                    b.ToTable("produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
